import { execSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const rootDir = resolve(__dirname, '..')
const packageJsonPath = resolve(rootDir, 'package.json')
const outputPath = resolve(rootDir, 'src/generated/app-version.ts')

function getGitCommitShortHash() {
  try {
    return execSync('git rev-parse --short HEAD', {
      cwd: rootDir,
      stdio: ['ignore', 'pipe', 'ignore'],
      encoding: 'utf-8',
    }).trim()
  } catch {
    return 'unknown'
  }
}

function getGitCommitCount() {
  try {
    return Number(
      execSync('git rev-list --count HEAD', {
        cwd: rootDir,
        stdio: ['ignore', 'pipe', 'ignore'],
        encoding: 'utf-8',
      }).trim(),
    )
  } catch {
    return 0
  }
}

function getCycleStartCommitCount(packageJson) {
  const rawValue = packageJson.versioning?.cycleStartCommitCount

  if (typeof rawValue === 'number' && Number.isFinite(rawValue)) {
    return rawValue
  }

  if (typeof rawValue === 'string' && rawValue.trim()) {
    const parsed = Number(rawValue)
    if (Number.isFinite(parsed)) {
      return parsed
    }
  }

  return 0
}

function getVersionParts(version) {
  const [major = '0', minor = '0'] = String(version).split('.')
  return { major, minor }
}

function getPatchCount(totalCommits, cycleStartCommitCount) {
  return Math.max(totalCommits - cycleStartCommitCount, 0)
}

const packageJsonRaw = readFileSync(packageJsonPath, 'utf-8')
const packageJson = JSON.parse(packageJsonRaw)

const gitCommit = getGitCommitShortHash()
const packageVersion = String(packageJson.version || '0.0.0')
const gitCommitCount = getGitCommitCount()
const cycleStartCommitCount = getCycleStartCommitCount(packageJson)
const isProductionBuild = process.env.NODE_ENV === 'production'
const { major, minor } = getVersionParts(packageVersion)
const patch = getPatchCount(gitCommitCount, cycleStartCommitCount)
const releaseVersion = `${major}.${minor}.${patch}`
const dynamicVersion = isProductionBuild
  ? releaseVersion
  : `${releaseVersion}-dev`
const appVersion = String(process.env.APP_VERSION || dynamicVersion)
const builtAt = new Date().toISOString()

const content = `// Auto-generated by scripts/generate-version.mjs
export const APP_VERSION = ${JSON.stringify(appVersion)} as const
export const APP_GIT_COMMIT = ${JSON.stringify(gitCommit)} as const
export const APP_BUILD_TIME = ${JSON.stringify(builtAt)} as const
`

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, content, 'utf-8')

console.log(`Generated ${outputPath}`)
