import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = resolve(__dirname, "..");
const packageJsonPath = resolve(rootDir, "package.json");
const outputPath = resolve(rootDir, "src/generated/app-version.ts");

function getGitCommitShortHash() {
  try {
    return execSync("git rev-parse --short HEAD", {
      cwd: rootDir,
      stdio: ["ignore", "pipe", "ignore"],
      encoding: "utf-8",
    }).trim();
  } catch {
    return "unknown";
  }
}

const packageJsonRaw = readFileSync(packageJsonPath, "utf-8");
const packageJson = JSON.parse(packageJsonRaw);

const appVersion = String(packageJson.version || "0.0.0");
const gitCommit = getGitCommitShortHash();
const builtAt = new Date().toISOString();

const content = `// Auto-generated by scripts/generate-version.mjs
export const APP_VERSION = ${JSON.stringify(appVersion)} as const;
export const APP_GIT_COMMIT = ${JSON.stringify(gitCommit)} as const;
export const APP_BUILD_TIME = ${JSON.stringify(builtAt)} as const;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, "utf-8");

console.log(`Generated ${outputPath}`);
