/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnavailableRouteImport } from './routes/unavailable'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWeeklyCashflowRouteImport } from './routes/app/weekly-cashflow'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppRegisterRouteImport } from './routes/app/register'
import { Route as AppRecurrencesRouteImport } from './routes/app/recurrences'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppConsolidatedRouteImport } from './routes/app/consolidated'
import { Route as AppCategoriesRouteImport } from './routes/app/categories'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppAccountsRouteImport } from './routes/app/accounts'
import { Route as AppAccountsIdRouteImport } from './routes/app/accounts/$id'

const UnavailableRoute = UnavailableRouteImport.update({
  id: '/unavailable',
  path: '/unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWeeklyCashflowRoute = AppWeeklyCashflowRouteImport.update({
  id: '/weekly-cashflow',
  path: '/weekly-cashflow',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecurrencesRoute = AppRecurrencesRouteImport.update({
  id: '/recurrences',
  path: '/recurrences',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConsolidatedRoute = AppConsolidatedRouteImport.update({
  id: '/consolidated',
  path: '/consolidated',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsIdRoute = AppAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unavailable': typeof UnavailableRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/consolidated': typeof AppConsolidatedRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recurrences': typeof AppRecurrencesRoute
  '/app/register': typeof AppRegisterRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/weekly-cashflow': typeof AppWeeklyCashflowRoute
  '/app/': typeof AppIndexRoute
  '/app/accounts/$id': typeof AppAccountsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unavailable': typeof UnavailableRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/consolidated': typeof AppConsolidatedRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recurrences': typeof AppRecurrencesRoute
  '/app/register': typeof AppRegisterRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/weekly-cashflow': typeof AppWeeklyCashflowRoute
  '/app': typeof AppIndexRoute
  '/app/accounts/$id': typeof AppAccountsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unavailable': typeof UnavailableRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/consolidated': typeof AppConsolidatedRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recurrences': typeof AppRecurrencesRoute
  '/app/register': typeof AppRegisterRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/weekly-cashflow': typeof AppWeeklyCashflowRoute
  '/app/': typeof AppIndexRoute
  '/app/accounts/$id': typeof AppAccountsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unavailable'
    | '/app/accounts'
    | '/app/audit'
    | '/app/categories'
    | '/app/consolidated'
    | '/app/profile'
    | '/app/recurrences'
    | '/app/register'
    | '/app/transactions'
    | '/app/weekly-cashflow'
    | '/app/'
    | '/app/accounts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unavailable'
    | '/app/accounts'
    | '/app/audit'
    | '/app/categories'
    | '/app/consolidated'
    | '/app/profile'
    | '/app/recurrences'
    | '/app/register'
    | '/app/transactions'
    | '/app/weekly-cashflow'
    | '/app'
    | '/app/accounts/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unavailable'
    | '/app/accounts'
    | '/app/audit'
    | '/app/categories'
    | '/app/consolidated'
    | '/app/profile'
    | '/app/recurrences'
    | '/app/register'
    | '/app/transactions'
    | '/app/weekly-cashflow'
    | '/app/'
    | '/app/accounts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnavailableRoute: typeof UnavailableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unavailable': {
      id: '/unavailable'
      path: '/unavailable'
      fullPath: '/unavailable'
      preLoaderRoute: typeof UnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/weekly-cashflow': {
      id: '/app/weekly-cashflow'
      path: '/weekly-cashflow'
      fullPath: '/app/weekly-cashflow'
      preLoaderRoute: typeof AppWeeklyCashflowRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/register': {
      id: '/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/recurrences': {
      id: '/app/recurrences'
      path: '/recurrences'
      fullPath: '/app/recurrences'
      preLoaderRoute: typeof AppRecurrencesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/consolidated': {
      id: '/app/consolidated'
      path: '/consolidated'
      fullPath: '/app/consolidated'
      preLoaderRoute: typeof AppConsolidatedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/accounts/$id': {
      id: '/app/accounts/$id'
      path: '/$id'
      fullPath: '/app/accounts/$id'
      preLoaderRoute: typeof AppAccountsIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsIdRoute: typeof AppAccountsIdRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsIdRoute: AppAccountsIdRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppRouteRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppConsolidatedRoute: typeof AppConsolidatedRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecurrencesRoute: typeof AppRecurrencesRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWeeklyCashflowRoute: typeof AppWeeklyCashflowRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppConsolidatedRoute: AppConsolidatedRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecurrencesRoute: AppRecurrencesRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWeeklyCashflowRoute: AppWeeklyCashflowRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnavailableRoute: UnavailableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
